/* PartyOrder: a local-first ordering app. Replace demo login with a server auth API before production. */
const CATEGORIES = [
  {id:'earings', name:'Earings', icon:'💎'},
  {id:'tops', name:'Tops', icon:'✨'},
  {id:'kalanki', name:'Kalanki', icon:'🌸'},
  {id:'groom-necklace', name:'Groom Necklace', icon:'📿'}
];
const STORE = 'party-order-v1';
const icons = ['💎','✨','🌸','📿','💠','🌟','🪷','🔶'];
const state = {user: JSON.parse(localStorage.getItem(STORE+'-user')||'null'), shop:JSON.parse(localStorage.getItem(STORE+'-shop')||'null'), category:'earings', cart:[], records:JSON.parse(localStorage.getItem(STORE+'-records')||'[]')};
const products = CATEGORIES.flatMap((cat, ci) => Array.from({length:100}, (_, i) => ({id:`${cat.id}-${i+1}`, category:cat.id, name:`${cat.name} Design ${String(i+1).padStart(3,'0')}`, price: [249,299,349,399][(i+ci)%4], icon:icons[(i+ci)%icons.length]})));
const money = n => `₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const save = () => {localStorage.setItem(STORE+'-user',JSON.stringify(state.user));localStorage.setItem(STORE+'-shop',JSON.stringify(state.shop));localStorage.setItem(STORE+'-records',JSON.stringify(state.records));};
const esc = s => String(s??'').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function render(){
  const app=document.querySelector('#app');
  if(!state.user){app.innerHTML=`<main class="auth-page"><section class="auth-card"><div class="brand"><span class="brand-mark">P</span> PartyOrder</div><h1>Welcome back</h1><p class="muted">Sign in to create and manage jewelry orders.</p><form id="login"><div class="field"><label>Email or username</label><input name="identity" required placeholder="owner@example.com"></div><div class="field"><label>Password</label><input name="password" type="password" required minlength="4" placeholder="••••••••"></div><div id="login-error" class="error"></div><button class="primary" style="width:100%">Sign in</button></form><p class="muted" style="font-size:12px;margin-top:22px">Demo mode: your account is stored only in this browser.</p></section></main>`;return;}
  if(!state.shop){app.innerHTML=`<main class="setup-wrap"><section class="setup-card"><div class="brand"><span class="brand-mark">P</span> PartyOrder</div><h1>Set up your shop</h1><p class="muted">This information appears on every invoice.</p><form id="shop-form"><div class="field"><label>Shop name</label><input name="shopName" required maxlength="80" placeholder="Shree Fashion Store"></div><div class="field"><label>Mobile number</label><input name="mobile" required pattern="[0-9 +()-]{7,20}" placeholder="9876543210"></div><div id="shop-error" class="error"></div><button class="primary">Save shop and continue</button></form></section></main>`;return;}
  const visible=products.filter(p=>p.category===state.category); const sub=state.cart.reduce((a,x)=>a+x.price*x.qty,0), gst=sub*.03, total=sub+gst;
  app.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand"><span class="brand-mark">P</span> PartyOrder</div><div class="top-actions"><span class="shop-pill">${esc(state.shop.name)}</span><button class="logout" id="logout">Sign out</button></div></header><main class="content"><div class="welcome"><div><h1>Good day, ${esc(state.shop.name)} 👋</h1><p class="muted">Choose products to create a new party order.</p></div><button class="secondary" id="new-order">Clear order</button></div><nav class="tabs">${CATEGORIES.map(c=>`<button class="tab ${c.id===state.category?'active':''}" data-cat="${c.id}">${c.icon} ${c.name}</button>`).join('')}</nav><div class="layout"><section><div class="catalog">${visible.map(p=>`<article class="product-card"><div class="product-art">${p.icon}</div><div class="product-body"><h3>${p.name}</h3><div class="price">${money(p.price)}</div><button class="add" data-add="${p.id}">Add to cart</button></div></article>`).join('')}</div></section><aside class="cart"><h2>Current order <span class="badge">${state.cart.length} items</span></h2>${state.cart.length?state.cart.map((x,i)=>`<div class="cart-row"><div class="row-head"><strong>${esc(x.name)}</strong><button class="remove" data-remove="${i}">Remove</button></div><div class="muted">${money(x.price)} each</div><div class="options"><input data-field="qty" data-index="${i}" type="number" min="1" value="${x.qty}" aria-label="Quantity"><input data-field="color" data-index="${i}" value="${esc(x.color)}" placeholder="Color"><select data-field="setting" data-index="${i}" aria-label="Color setting"><option ${x.setting==='Standard'?'selected':''}>Standard</option><option ${x.setting==='Gold'?'selected':''}>Gold</option><option ${x.setting==='Silver'?'selected':''}>Silver</option><option ${x.setting==='Rose gold'?'selected':''}>Rose gold</option></select></div></div>`).join(''):`<div class="cart-empty">Your cart is empty.<br>Click “Add to cart” on a product.</div>`}<div class="totals"><div class="total-line"><span>Subtotal</span><strong>${money(sub)}</strong></div><div class="total-line"><span>GST (3%)</span><strong>${money(gst)}</strong></div><div class="total-line grand"><span>Total</span><strong>${money(total)}</strong></div></div><div class="cart-actions"><button class="secondary" id="print" ${state.cart.length?'':'disabled'}>Print invoice</button><button class="primary" id="save-order" ${state.cart.length?'':'disabled'}>Save customer</button></div></aside></div><section class="records"><h2>Saved customers / invoices</h2>${state.records.length?state.records.slice().reverse().map(r=>`<div class="record"><div><strong>${esc(r.shop)}</strong><span class="muted">${r.date} · ${r.items} products · ${money(r.total)}</span></div><span class="badge">Saved</span></div>`).join(''):`<p class="muted">Saved invoices will appear here after you save an order.</p>`}</section></main></div>`;
  bind();
}
function bind(){document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;render()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.add), found=state.cart.find(x=>x.id===p.id);if(found)found.qty++;else state.cart.push({...p,qty:1,color:'',setting:'Standard'});render()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.cart.splice(+b.dataset.remove,1);render()});document.querySelectorAll('[data-field]').forEach(el=>el.onchange=()=>{const x=state.cart[+el.dataset.index];x[el.dataset.field]=el.dataset.field==='qty'?Math.max(1,+el.value||1):el.value;render()});document.querySelector('#logout').onclick=()=>{state.user=null;state.shop=null;save();render()};document.querySelector('#new-order').onclick=()=>{state.cart=[];render()};document.querySelector('#print').onclick=()=>window.print();document.querySelector('#save-order').onclick=saveOrder}
function saveOrder(){const sub=state.cart.reduce((a,x)=>a+x.price*x.qty,0), total=sub*1.03;state.records.push({shop:state.shop.name,date:new Date().toLocaleString('en-IN'),items:state.cart.reduce((a,x)=>a+x.qty,0),total:Number(total.toFixed(2))});save();alert('Invoice saved for '+state.shop.name+'. You can print it now.');window.print();state.cart=[];render()}
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='login'){const f=new FormData(e.target);if(f.get('password').length<4){document.querySelector('#login-error').textContent='Password must contain at least 4 characters.';return}state.user={identity:f.get('identity')};save();render()}if(e.target.id==='shop-form'){const f=new FormData(e.target), mobile=f.get('mobile').replace(/\D/g,'');if(mobile.length<7){document.querySelector('#shop-error').textContent='Enter a valid mobile number.';return}state.shop={name:f.get('shopName').trim(),mobile};save();render()}});
render();
